enum HAITYPE{
	WANZU_1=0,WANZU_2,WANZU_3,WANZU_4,WANZU_5,WANZU_6,WANZU_7,WANZU_8,WANZU_9,
	SOUZU_1,SOUZU_2,SOUZU_3,SOUZU_4,SOUZU_5,SOUZU_6,SOUZU_7,SOUZU_8,SOUZU_9,
	PINZU_1,PINZU_2,PINZU_3,PINZU_4,PINZU_5,PINZU_6,PINZU_7,PINZU_8,PINZU_9,
	TONN,NANN,SHA,PEI,HAKU,HATSU,TYUNN,WANZU_AKA,PINZU_AKA,SOUZU_AKA,HAI_END
};